services:
  - type: web
    name: periodontal-recall-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: greddy213041974@gmail.com
      - key: SMTP_PASS
        value: vxjjxeypeinknxhm
      - key: SMTP_FROM
        value: greddy213041974@gmail.com
      - key: UPLOAD_FOLDER
        value: uploads
      - key: DB_HOST
        fromDatabase:
          name: periodontal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: periodontal-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: periodontal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: periodontal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: periodontal-db
          property: password

databases:
  - name: periodontal-db
    plan: free
    databaseName: periodontal_recall_ai
    user: app_user
